### ISSUE TITLE
Test failures to address

### ISSUE THREAD

**Issue by justaugustus** [openclarity/functionclarity#69]
Seeing the following build failures from https://github.com/openclarity/functionclarity/actions/runs/3482235999/jobs/5824417904 / https://github.com/openclarity/functionclarity/pull/68:

### Test

```log
Run test/e2e_test.sh
  test/e2e_test.sh
  shell: /usr/bin/bash -e {0}
  env:
    ACCESS_KEY: 
    SECRET_KEY: 
    BUCKET: 
    REGION: 
    FUNCTION_REGION: 
    jwt_token: 
    COSIGN_EXPERIMENTAL: 0
    is_start: true
    uuid: 1fdbd120-65e1-11ed-84fa-bfaf52f8ea8e
starting...
aws_function binary copied to test folder
testing lambda built successfully
stack template copied to test folder
e2e tests started
uuid: 1fdbd120-65e1-11ed-84fa-bfaf52f8ea8e
2022/11/16 19:01:56 operation error ECR: GetAuthorizationToken, failed to resolve service endpoint, an AWS region is required, but was not found
exit status 1
FAIL	github.com/openclarity/function-clarity/test	0.044s
```

### Get IdToken

```log
Run actions/github-script@v6
  with:
    script: const coredemo = require('@actions/core')
  let id_token = await coredemo.getIDToken("sigstore")   
  coredemo.setOutput('id_token', id_token)
  
    github-token: ***
    debug: false
    user-agent: actions/github-script
    result-encoding: json
    retries: 0
    retry-exempt-status-codes: 400,401,403,404,422
Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
    at Function.<anonymous> (/home/runner/work/functionclarity/functionclarity/node_modules/@actions/core/lib/oidc-utils.js:71:23)
    at Generator.next (<anonymous>)
    at /home/runner/work/functionclarity/functionclarity/node_modules/@actions/core/lib/oidc-utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/functionclarity/functionclarity/node_modules/@actions/core/lib/oidc-utils.js:4:12)
    at Function.getIDToken (/home/runner/work/functionclarity/functionclarity/node_modules/@actions/core/lib/oidc-utils.js:57:16)
    at Object.<anonymous> (/home/runner/work/functionclarity/functionclarity/node_modules/@actions/core/lib/core.js:308:46)
    at Generator.next (<anonymous>)
    at /home/runner/work/functionclarity/functionclarity/node_modules/@actions/core/lib/core.js:27:71
    at new Promise (<anonymous>)
Error: Unhandled error: Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
```

### KeylessTest

```log
Run test/e2e_test_keyless.sh
  test/e2e_test_keyless.sh
  shell: /usr/bin/bash -e {0}
  env:
    ACCESS_KEY: 
    SECRET_KEY: 
    BUCKET: 
    REGION: 
    FUNCTION_REGION: 
    jwt_token: 
    COSIGN_EXPERIMENTAL: 1
    is_start: false
    uuid: 1fdbd120-65e1-11ed-84fa-bfaf52f8ea8e
starting...
aws_function binary copied to test folder
testing lambda built successfully
stack template copied to test folder
e2e tests started
uuid: 1fdbd120-65e1-11ed-84fa-bfaf52f8ea8e
2022/11/16 19:02:03 operation error ECR: GetAuthorizationToken, failed to resolve service endpoint, an AWS region is required, but was not found
exit status 1
FAIL	github.com/openclarity/function-clarity/test	0.032s
Error: Process completed with exit code 1.
```

**Comment by justaugustus** [comment]
I pushed an initial step to split out tests in https://github.com/openclarity/functionclarity/pull/77.

**Comment by justaugustus** [comment]
@openclarity/functionclarity-maintainers -- do we have an update on this one? The test presubmits are still failing.

**Comment by lelia** [comment]
This project has been publicly archived. Please visit **[github.com/openclarity](https://github.com/openclarity)** or **[openclarity.io](https://openclarity.io)** to discover our other projects!
